// salsun2d_kernel.cpp
//
// Vitis kernel for Alveo U250 that runs SA-LSUN 2-D analysis, coefficient
// mask and synthesis (generated by HDL Coder) on a sequence of frames in
// global memory. Define SALSUN2D_OPT to use salsun2d_hls_opt instead of
// salsun2d_hls.
//
//   src        : num_frames frames of SZY x SZX single, MATLAB column-major
//   params     : NPARAMS values packed by salsun2d_pack_params
//   dst        : reconstructed frames, same layout as src
//   num_frames : number of frames
//
// The parameters are read into on-chip memory once per call and reused
// for all frames.
//
// Copyright (c) 2026, Shogo MURAMATSU
//
// All rights reserved.
//
// Contact address: Shogo MURAMATSU,
//    Faculty of Engineering, Niigata University,
//    8050 2-no-cho Ikarashi, Nishi-ku,
//    Niigata, 950-2181, JAPAN
//
// http://msiplab.eng.niigata-u.ac.jp/
//

#ifdef SALSUN2D_OPT
#include "salsun2d_hls_optClass.hpp"
typedef salsun2d_hls_optClass Design;
#define RUN_DESIGN(dut, x, w, y) dut.salsun2d_hls_opt(x, w, y)
#else
#include "salsun2d_hlsClass.hpp"
typedef salsun2d_hlsClass Design;
#define RUN_DESIGN(dut, x, w, y) dut.salsun2d_hls(x, w, y)
#endif

#ifndef SZY
#define SZY 300
#endif
#ifndef SZX
#define SZX 300
#endif
#ifndef NPARAMS
#define NPARAMS 489085
#endif

static const int FRAME_SIZE = SZY * SZX;

extern "C" {

void salsun2d_kernel(const float *src, const float *params, float *dst, int num_frames)
{
#pragma HLS INTERFACE m_axi port = src offset = slave bundle = gmem0 depth = FRAME_SIZE
#pragma HLS INTERFACE m_axi port = params offset = slave bundle = gmem1 depth = NPARAMS
#pragma HLS INTERFACE m_axi port = dst offset = slave bundle = gmem0 depth = FRAME_SIZE
#pragma HLS INTERFACE s_axilite port = num_frames
#pragma HLS INTERFACE s_axilite port = return

    // Static so that software emulation does not place them on the stack
    static real32_T w[NPARAMS];
    static real32_T x[SZX][SZY];
    static real32_T y[SZX][SZY];
    static Design dut;
#pragma HLS BIND_STORAGE variable = w type = ram_2p impl = uram

load_params:
    for (int i = 0; i < NPARAMS; i++) {
#pragma HLS PIPELINE II = 1
        w[i] = params[i];
    }

frame_loop:
    for (int f = 0; f < num_frames; f++) {
    load_frame:
        for (int i = 0; i < FRAME_SIZE; i++) {
#pragma HLS PIPELINE II = 1
            x[i / SZY][i % SZY] = src[f * FRAME_SIZE + i];
        }

        RUN_DESIGN(dut, x, w, y);

    store_frame:
        for (int i = 0; i < FRAME_SIZE; i++) {
#pragma HLS PIPELINE II = 1
            dst[f * FRAME_SIZE + i] = y[i / SZY][i % SZY];
        }
    }
}

}
