// salsun2d_band_kernel.cpp
//
// Vitis kernel for Alveo U250 that runs SA-LSUN 2-D analysis, coefficient
// mask and synthesis of one frame band by band (overlap-save), with the
// band design salsun2d_hls_band generated by HDL Coder.
//
//   src       : one frame, SZY x SZX single, MATLAB column-major
//   params    : NPARAMS values packed by salsun2d_pack_params
//   stats_in  : standardization statistics mu (NDEC x NEST) followed by
//               sigma (NDEC x NEST), column-major, from the previous frames
//   dst       : reconstructed frame, same layout as src
//   stats_out : sums (NDEC x NEST) and sums of squares (NDEC x NEST) of the
//               estimator input channels over the blocks of this frame,
//               for the statistics of the next frame
//
// Bands of BAND block rows start at 0, BAND, 2*BAND, ...; the last band is
// moved up so that it ends at the last block row, and its sums are scaled
// by the share of rows it adds (as in salsun2d_band_frame.m). Each band
// is loaded with HALO block rows of circular context above and below.
// The parameters are read into on-chip memory once per call.
//
// Copyright (c) 2026, Shogo MURAMATSU
//
// All rights reserved.
//
// Contact address: Shogo MURAMATSU,
//    Faculty of Engineering, Niigata University,
//    8050 2-no-cho Ikarashi, Nishi-ku,
//    Niigata, 950-2181, JAPAN
//
// http://msiplab.eng.niigata-u.ac.jp/
//

#include "salsun2d_hls_bandClass.hpp"

#ifndef SZY
#define SZY 300
#endif
#ifndef SZX
#define SZX 300
#endif
#ifndef BAND
#define BAND 31
#endif
#ifndef HALO
#define HALO 7
#endif
#ifndef NPARAMS
#define NPARAMS 489085
#endif
#define NDEC 16
#define NEST 5
#define MY 4

static const int NROWS = SZY / MY;             // block rows of the frame
static const int SUBROWS = BAND + 2 * HALO;    // block rows of a band with halo
static const int SUBPIX = SUBROWS * MY;        // pixel rows of a band with halo
static const int BANDPIX = BAND * MY;          // pixel rows of a band
static const int NSTATS = NDEC * NEST;

extern "C" {

void salsun2d_band_kernel(const float *src, const float *params, const float *stats_in,
                          float *dst, float *stats_out)
{
#pragma HLS INTERFACE m_axi port = src offset = slave bundle = gmem0 depth = SZY * SZX
#pragma HLS INTERFACE m_axi port = params offset = slave bundle = gmem1 depth = NPARAMS
#pragma HLS INTERFACE m_axi port = stats_in offset = slave bundle = gmem1 depth = 2 * NSTATS
#pragma HLS INTERFACE m_axi port = dst offset = slave bundle = gmem0 depth = SZY * SZX
#pragma HLS INTERFACE m_axi port = stats_out offset = slave bundle = gmem1 depth = 2 * NSTATS
#pragma HLS INTERFACE s_axilite port = return

    // Static so that software emulation does not place them on the stack
    static real32_T w[NPARAMS];
    static real32_T xb[SZX][SUBPIX];
    static real32_T yb[SZX][BANDPIX];
    static real32_T mu[NEST][NDEC];
    static real32_T sigma[NEST][NDEC];
    static real32_T sum1[NEST][NDEC];
    static real32_T sum2[NEST][NDEC];
    static real32_T acc1[NEST][NDEC];
    static real32_T acc2[NEST][NDEC];
    static salsun2d_hls_bandClass dut;
// Two 32-bit values per 72-bit URAM word; the band input stays in BRAM
#pragma HLS ARRAY_RESHAPE variable = w type = cyclic factor = 2
#pragma HLS BIND_STORAGE variable = w type = ram_2p impl = uram

load_params:
    for (int i = 0; i < NPARAMS; i++) {
#pragma HLS PIPELINE II = 1
        w[i] = params[i];
    }
load_stats:
    for (int i = 0; i < NSTATS; i++) {
#pragma HLS PIPELINE II = 1
        mu[i / NDEC][i % NDEC] = stats_in[i];
        sigma[i / NDEC][i % NDEC] = stats_in[NSTATS + i];
        acc1[i / NDEC][i % NDEC] = 0.0f;
        acc2[i / NDEC][i % NDEC] = 0.0f;
    }

    int prev_start = -BAND;
band_loop:
    for (int r0 = 0; r0 < NROWS; r0 += BAND) {
        if (r0 + BAND > NROWS) {
            r0 = NROWS - BAND;           // move the last band up
        }
        // Rows of the band already produced by the previous band
        const int repeated = (prev_start + BAND > r0) ? (prev_start + BAND - r0) : 0;
        prev_start = r0;

    load_band:
        for (int c = 0; c < SZX; c++) {
            for (int i = 0; i < SUBPIX; i++) {
#pragma HLS PIPELINE II = 1
                int brow = r0 - HALO + i / MY;            // block row in the frame
                brow = ((brow % NROWS) + NROWS) % NROWS;  // circular
                xb[c][i] = src[c * SZY + brow * MY + i % MY];
            }
        }

        dut.salsun2d_hls_band(xb, w, mu, sigma, yb, sum1, sum2);

    store_band:
        for (int c = 0; c < SZX; c++) {
            for (int i = 0; i < BANDPIX; i++) {
#pragma HLS PIPELINE II = 1
                dst[c * SZY + r0 * MY + i] = yb[c][i];
            }
        }
        const float share = (float)(BAND - repeated) / (float)BAND;
    accumulate:
        for (int i = 0; i < NSTATS; i++) {
#pragma HLS PIPELINE II = 1
            acc1[i / NDEC][i % NDEC] += sum1[i / NDEC][i % NDEC] * share;
            acc2[i / NDEC][i % NDEC] += sum2[i / NDEC][i % NDEC] * share;
        }
    }

store_stats:
    for (int i = 0; i < NSTATS; i++) {
#pragma HLS PIPELINE II = 1
        stats_out[i] = acc1[i / NDEC][i % NDEC];
        stats_out[NSTATS + i] = acc2[i / NDEC][i % NDEC];
    }
}

}
